### ISSUE TITLE
Update to php 8 is incomplete, because browscap < 5.0.0 does not allow php 8

### ISSUE THREAD

**Issue by thirsch** [kulbakin/laravel-browscap#18]
Did you have any success on using laravel-browscap 2.0.8 on a php 8 project? For me, browscap 4.3 can not be installed on php 8 and I have to manually override the version in my installation like `"browscap/browscap-php": "5.0.0 as 4.3.0",` in my composer.json

**Comment by kulbakin** [comment]
browscap requirement for php say "php": ">=7.3.0,<8.1.0" so maybe you are using some beta version of php which is >= 8.1

**Comment by thirsch** [comment]
That's true, but only for browscap-php >= 5.0 and this lib is using ^4.0

**Comment by kulbakin** [comment]
yes indeed, to support php 8 browscap requirement must be  >= 5.0

**Comment by kulbakin** [comment]
Added browscap 5 as allowed version for the library, so the issue must be solved now

**Comment by thirsch** [comment]
Thank you!
