### ISSUE TITLE
Found 1 security vulnerability advisory affecting 1 package.

### ISSUE THREAD

**Issue by guilhermekfagundes** [kulbakin/laravel-browscap#23]
When installing the package it gives information that it has a vulnerability

![Captura de tela de 2023-05-05 19-12-08](https://user-images.githubusercontent.com/21370210/236577286-64ed5e71-b443-470d-8364-a0b0b6cdb9e6.png)

**Comment by kulbakin** [comment]
The affected package is not among required explicitly. 
The security issue is with *guzzlehttp*, if it indeed exists. The report should go there.
