### ISSUE TITLE
Prepare to release new version to match Browscap 4.0

### ISSUE THREAD

**Issue by vv12131415** [kulbakin/laravel-browscap#3]
The [Browscap 4.0 is almost ready](https://github.com/browscap/browscap-php/milestones) we/you/me should prepare service provider to match it.

**Comment by kulbakin** [comment]
@vladyslavstartsev 
I appreciate your updates, even more so if you also ensure support for Browscap 4.0 :)
When this happen, we create new 2.0 release for the package, so there shouldn't be any compatibility issues

**Comment by vv12131415** [comment]
@kulbakin I'm back!
Will try to release it somehow this month. 
BTW, should I update it to 4.0 or right now even to 4.1?

**Comment by kulbakin** [comment]
@vladyslavstartsev would be great!

**Comment by kulbakin** [comment]
merged pull #5 
@vladyslavstartsev thanks!
