### ISSUE TITLE
Exception with Browscap-Fascade

### ISSUE THREAD

**Issue by gemini-git** [kulbakin/laravel-browscap#7]
I got the following exception while trying to use the fascade:

"Call to undefined method Illuminate\Log\Writer::driver()"

Changing "$app->make('log')->driver()" to "$app->make('log')" in BrowscapServiceProvider.php seems to solve the problem.

**Comment by kulbakin** [comment]
@geminixxl what version of Laravel are you using?

**Comment by gemini-git** [comment]
I'm using the lts version (laravel 5.5)

**Comment by bitfactory-timon-vandermeulen** [comment]
Running into this issue as well. To 'fix' it i am not using the Facade provided and initiate the class manually with the change in the pull request like this:

`$cache = new SimpleCacheAdapter(
                new FilesystemCache(config('browscap.cache'))
            );
            $bc = new Browscap(
                $cache,
                app()->make('log')
            );
`
